spring:
  cloud:
    stream:
    #EinAusChannel
      bindings:
        jobCreation:
          destination: wacodis.jobs.creation22
          binder: wacodis_rabbit
          content-type: application/json
      #MessageBroker
      binders:
        wacodis_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: eum-dcsi.demo.52north.org
                port: 5672
                username: rabbitmq
                password: rabbitmq